### ISSUE TITLE
Support for ForeignKeyConstraint with ON UPDATE/DELETE CASCADE

### ISSUE THREAD

**Issue by dr-rodriguez** [lsst/felis#126]
While testing the design of some schemas, I noticed that any Foreign Keys get saved without UPDATE/DELETE CASCADE specifications. That's probably fine in most cases, but there are situations where having that can be useful.    
Is that something that is supported but not documented? Or perhaps it's something that is beyond the scope of this package?

Example:
```yaml
  - name: Names
    "@id": "#Names"
    description: "Additional identifiers for objects in Sources table"
    primaryKey:
    - "#Names.id"
    - "#Names.name"

    columns:
    - name: id
      "@id": "#Names.id"
      datatype: long
      description: Main identifier for an object; links to Sources table
      nullable: false
    - name: name
      "@id": "#Names.name"
      datatype: string
      length: 100
      description: Identifier for source
      nullable: false

    constraints:
      - name: Names_id_Sources_id
        "@type": "ForeignKey"
        "@id": "#FK_Names_id_Source_id"
        description: Link Names to Sources table
        columns:
        - "#Names.id"
        referencedColumns:
        - "#Sources.id"
```

produces Postgres sql of the form:
```sql
CREATE TABLE exomast."Names" (
	id BIGINT NOT NULL, 
	name VARCHAR(100) NOT NULL, 
	PRIMARY KEY (id, name), 
	CONSTRAINT "Names_id_Sources_id" FOREIGN KEY(id) REFERENCES exomast."Sources" (id)
)

;
COMMENT ON TABLE exomast."Names" IS 'Additional identifiers for objects in Sources table';
COMMENT ON COLUMN exomast."Names".id IS 'Main identfier for an object; links to Sources table';
COMMENT ON COLUMN exomast."Names".name IS 'Identifier for source';
COMMENT ON CONSTRAINT "Names_id_Sources_id" ON exomast."Names" IS 'Link Names to Sources table';
```

But I would have wanted the foreign key to be something like:
```sql
CONSTRAINT "Names_id_Sources_id" FOREIGN KEY(id) REFERENCES exomast."Sources" (id) ON DELETE CASCADE 
```
so that if I delete the entry from _Sources_ all of its references in _Names_ are deleted.
